"""add_created_at_to_books

Revision ID: 469bc121699c
Revises: 
Create Date: 2026-02-02 15:53:34.606631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '469bc121699c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('books', 'total_copies',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('books', 'available_copies',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('loans', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('loans_ibfk_1'), 'loans', type_='foreignkey')
    op.drop_constraint(op.f('loans_ibfk_2'), 'loans', type_='foreignkey')
    op.create_foreign_key(None, 'loans', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'loans', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.create_foreign_key(op.f('loans_ibfk_2'), 'loans', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('loans_ibfk_1'), 'loans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('loans', 'due_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('books', 'available_copies',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('books', 'total_copies',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###
